### ISSUE TITLE
Upgrade to TYPO3 11

### ISSUE THREAD

**Issue by Hobokens** [SicorDev/sic_address#51]
Hi,
do you have a schedule to upgrade this nice extension to the next TYPO3 version?

Thanks for your work and kind regards
Hobokens

**Comment by SicorDev** [comment]
Hi, we're still working on our first TYPO3 11 project to actually go live with sic_address before releasing it to TER. It's always good to have a working reference first. Do you experience any issues with the GIT master on TYPO3 11?

**Comment by Hobokens** [comment]
Yes, please take a look at #50.

**Comment by Hobokens** [comment]
TYPO3 11.5.15
tt_address 6.0.1
sic_address GIT master

Error in FE:

```
#1472064775: Unknown column 'last_name' in 'field list' | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /var/www/vhosts/xxxx.my-provider.de/httpdocs/typo3cms/typo3_src-11.5.14/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 296. Requested URL: https://www.xxxxx.my-provider.de/lehre-a-z 
```

View - List
A-Z Field - last_name
Order field - last_name

**Comment by SicorDev** [comment]
Yes, it's not working with tt_address 6 at the moment.

**Comment by Hobokens** [comment]
@SicorDev with tt_address 5.3. I get the following error

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\Extbase\Pagination\QueryResultPaginator::__construct() must implement interface TYPO3\CMS\Extbase\Persistence\QueryResultInterface, null given, called in /var/www/vhosts/XXX.my-provider.de/httpdocs/typo3cms/typo3_src-11.5.17/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3220 | TypeError thrown in file /var/www/vhosts/900677.jweiland-hosting.de/httpdocs/typo3cms/typo3_src-11.5.17/typo3/sysext/extbase/Classes/Pagination/QueryResultPaginator.php in line 35. Requested URL: https://www.XXX.my-provider.de/lehre-a-z `

**Comment by SicorDev** [comment]
I just released Version 4.0.0 officially for TYPO3 11. I have a project were it's running fine together with tt_address 6.1.0.
Can you possibly try this combo and see if you still get any errors?

**Comment by SicorDev** [comment]
I think I fixed it with the latest commit to:
sic_address\Classes\Controller\AddressController.php

Does it work for you now?

**Comment by Hobokens** [comment]
Thanks for your quick response. Unfortunately the error remains when I select 'Do not show all datasets by default '.

**Comment by Hobokens** [comment]
I'm sorry, but I can't help in the technical question.
Can you reproduce the problem on your system?

**Comment by SicorDev** [comment]
I had another run at fixing this, please update this file again from master:
sic_address\Classes\Controller\AddressController.php

Does it work for you now?

**Comment by Hobokens** [comment]
Nice, the new fix solves the problem. 
Thanks a lot for your work.
